[package]
name = "csp_project_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
core_affinity = "0.8.1"
criterion = "0.5.1"
rand = "0.8.5"
